/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PtRouteImport } from './routes/pt'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PerformanceIndexRouteImport } from './routes/performance/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as GxIndexRouteImport } from './routes/gx/index'
import { Route as ClassesIndexRouteImport } from './routes/classes/index'
import { Route as AvailabilityIndexRouteImport } from './routes/availability/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as ScheduleSessionIdRouteImport } from './routes/schedule/$sessionId'
import { Route as MessagesThreadIdRouteImport } from './routes/messages/$threadId'
import { Route as MembersMemberIdRouteImport } from './routes/members/$memberId'
import { Route as GxClassIdRouteImport } from './routes/gx/$classId'
import { Route as ClassesClassIdRouteImport } from './routes/classes/$classId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const PerformanceIndexRoute = PerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const GxIndexRoute = GxIndexRouteImport.update({
  id: '/gx/',
  path: '/gx/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityIndexRoute = AvailabilityIndexRouteImport.update({
  id: '/availability/',
  path: '/availability/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleSessionIdRoute = ScheduleSessionIdRouteImport.update({
  id: '/schedule/$sessionId',
  path: '/schedule/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/messages/$threadId',
  path: '/messages/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const GxClassIdRoute = GxClassIdRouteImport.update({
  id: '/gx/$classId',
  path: '/gx/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdRoute = ClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteWithChildren
  '/pt': typeof PtRoute
  '/auth/login': typeof AuthLoginRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/gx/$classId': typeof GxClassIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/schedule/$sessionId': typeof ScheduleSessionIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/gx/': typeof GxIndexRoute
  '/members/': typeof MembersIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/performance/': typeof PerformanceIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pt': typeof PtRoute
  '/auth/login': typeof AuthLoginRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/gx/$classId': typeof GxClassIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/schedule/$sessionId': typeof ScheduleSessionIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/availability': typeof AvailabilityIndexRoute
  '/classes': typeof ClassesIndexRoute
  '/gx': typeof GxIndexRoute
  '/members': typeof MembersIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/performance': typeof PerformanceIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteWithChildren
  '/pt': typeof PtRoute
  '/auth/login': typeof AuthLoginRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/gx/$classId': typeof GxClassIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/schedule/$sessionId': typeof ScheduleSessionIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/gx/': typeof GxIndexRoute
  '/members/': typeof MembersIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/performance/': typeof PerformanceIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/pt'
    | '/auth/login'
    | '/classes/$classId'
    | '/gx/$classId'
    | '/members/$memberId'
    | '/messages/$threadId'
    | '/schedule/$sessionId'
    | '/sessions/$sessionId'
    | '/availability/'
    | '/classes/'
    | '/gx/'
    | '/members/'
    | '/messages/'
    | '/performance/'
    | '/profile/'
    | '/schedule/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pt'
    | '/auth/login'
    | '/classes/$classId'
    | '/gx/$classId'
    | '/members/$memberId'
    | '/messages/$threadId'
    | '/schedule/$sessionId'
    | '/sessions/$sessionId'
    | '/availability'
    | '/classes'
    | '/gx'
    | '/members'
    | '/messages'
    | '/performance'
    | '/profile'
    | '/schedule'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/pt'
    | '/auth/login'
    | '/classes/$classId'
    | '/gx/$classId'
    | '/members/$memberId'
    | '/messages/$threadId'
    | '/schedule/$sessionId'
    | '/sessions/$sessionId'
    | '/availability/'
    | '/classes/'
    | '/gx/'
    | '/members/'
    | '/messages/'
    | '/performance/'
    | '/profile/'
    | '/schedule/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  PtRoute: typeof PtRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ClassesClassIdRoute: typeof ClassesClassIdRoute
  GxClassIdRoute: typeof GxClassIdRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
  ScheduleSessionIdRoute: typeof ScheduleSessionIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  AvailabilityIndexRoute: typeof AvailabilityIndexRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  GxIndexRoute: typeof GxIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  PerformanceIndexRoute: typeof PerformanceIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/performance/': {
      id: '/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof PerformanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gx/': {
      id: '/gx/'
      path: '/gx'
      fullPath: '/gx/'
      preLoaderRoute: typeof GxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability/': {
      id: '/availability/'
      path: '/availability'
      fullPath: '/availability/'
      preLoaderRoute: typeof AvailabilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$sessionId': {
      id: '/schedule/$sessionId'
      path: '/schedule/$sessionId'
      fullPath: '/schedule/$sessionId'
      preLoaderRoute: typeof ScheduleSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gx/$classId': {
      id: '/gx/$classId'
      path: '/gx/$classId'
      fullPath: '/gx/$classId'
      preLoaderRoute: typeof GxClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId': {
      id: '/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRouteWithChildren,
  PtRoute: PtRoute,
  AuthLoginRoute: AuthLoginRoute,
  ClassesClassIdRoute: ClassesClassIdRoute,
  GxClassIdRoute: GxClassIdRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  MessagesThreadIdRoute: MessagesThreadIdRoute,
  ScheduleSessionIdRoute: ScheduleSessionIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  AvailabilityIndexRoute: AvailabilityIndexRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  GxIndexRoute: GxIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  PerformanceIndexRoute: PerformanceIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
