/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZatcaRouteImport } from './routes/zatca'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as RolesRoleIdRouteImport } from './routes/roles/$roleId'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations/$orgId'
import { Route as MembersMemberIdRouteImport } from './routes/members/$memberId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as OrganizationsOrgIdClubsClubIdRouteImport } from './routes/organizations/$orgId.clubs.$clubId'
import { Route as OrganizationsOrgIdClubsClubIdBranchesBranchIdRouteImport } from './routes/organizations/$orgId.clubs.$clubId.branches.$branchId'

const ZatcaRoute = ZatcaRouteImport.update({
  id: '/zatca',
  path: '/zatca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleIdRoute = RolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgIdClubsClubIdRoute =
  OrganizationsOrgIdClubsClubIdRouteImport.update({
    id: '/clubs/$clubId',
    path: '/clubs/$clubId',
    getParentRoute: () => OrganizationsOrgIdRoute,
  } as any)
const OrganizationsOrgIdClubsClubIdBranchesBranchIdRoute =
  OrganizationsOrgIdClubsClubIdBranchesBranchIdRouteImport.update({
    id: '/branches/$branchId',
    path: '/branches/$branchId',
    getParentRoute: () => OrganizationsOrgIdClubsClubIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/zatca': typeof ZatcaRoute
  '/auth/login': typeof AuthLoginRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/members/': typeof MembersIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/organizations/$orgId/clubs/$clubId': typeof OrganizationsOrgIdClubsClubIdRouteWithChildren
  '/organizations/$orgId/clubs/$clubId/branches/$branchId': typeof OrganizationsOrgIdClubsClubIdBranchesBranchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/zatca': typeof ZatcaRoute
  '/auth/login': typeof AuthLoginRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/members': typeof MembersIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/organizations/$orgId/clubs/$clubId': typeof OrganizationsOrgIdClubsClubIdRouteWithChildren
  '/organizations/$orgId/clubs/$clubId/branches/$branchId': typeof OrganizationsOrgIdClubsClubIdBranchesBranchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/zatca': typeof ZatcaRoute
  '/auth/login': typeof AuthLoginRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/members/': typeof MembersIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/organizations/$orgId/clubs/$clubId': typeof OrganizationsOrgIdClubsClubIdRouteWithChildren
  '/organizations/$orgId/clubs/$clubId/branches/$branchId': typeof OrganizationsOrgIdClubsClubIdBranchesBranchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/zatca'
    | '/auth/login'
    | '/members/$memberId'
    | '/organizations/$orgId'
    | '/roles/$roleId'
    | '/members/'
    | '/organizations/'
    | '/roles/'
    | '/organizations/$orgId/clubs/$clubId'
    | '/organizations/$orgId/clubs/$clubId/branches/$branchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/zatca'
    | '/auth/login'
    | '/members/$memberId'
    | '/organizations/$orgId'
    | '/roles/$roleId'
    | '/members'
    | '/organizations'
    | '/roles'
    | '/organizations/$orgId/clubs/$clubId'
    | '/organizations/$orgId/clubs/$clubId/branches/$branchId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/zatca'
    | '/auth/login'
    | '/members/$memberId'
    | '/organizations/$orgId'
    | '/roles/$roleId'
    | '/members/'
    | '/organizations/'
    | '/roles/'
    | '/organizations/$orgId/clubs/$clubId'
    | '/organizations/$orgId/clubs/$clubId/branches/$branchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ZatcaRoute: typeof ZatcaRoute
  AuthLoginRoute: typeof AuthLoginRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRouteWithChildren
  RolesRoleIdRoute: typeof RolesRoleIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zatca': {
      id: '/zatca'
      path: '/zatca'
      fullPath: '/zatca'
      preLoaderRoute: typeof ZatcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleId': {
      id: '/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof RolesRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId/clubs/$clubId': {
      id: '/organizations/$orgId/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/organizations/$orgId/clubs/$clubId'
      preLoaderRoute: typeof OrganizationsOrgIdClubsClubIdRouteImport
      parentRoute: typeof OrganizationsOrgIdRoute
    }
    '/organizations/$orgId/clubs/$clubId/branches/$branchId': {
      id: '/organizations/$orgId/clubs/$clubId/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/organizations/$orgId/clubs/$clubId/branches/$branchId'
      preLoaderRoute: typeof OrganizationsOrgIdClubsClubIdBranchesBranchIdRouteImport
      parentRoute: typeof OrganizationsOrgIdClubsClubIdRoute
    }
  }
}

interface OrganizationsOrgIdClubsClubIdRouteChildren {
  OrganizationsOrgIdClubsClubIdBranchesBranchIdRoute: typeof OrganizationsOrgIdClubsClubIdBranchesBranchIdRoute
}

const OrganizationsOrgIdClubsClubIdRouteChildren: OrganizationsOrgIdClubsClubIdRouteChildren =
  {
    OrganizationsOrgIdClubsClubIdBranchesBranchIdRoute:
      OrganizationsOrgIdClubsClubIdBranchesBranchIdRoute,
  }

const OrganizationsOrgIdClubsClubIdRouteWithChildren =
  OrganizationsOrgIdClubsClubIdRoute._addFileChildren(
    OrganizationsOrgIdClubsClubIdRouteChildren,
  )

interface OrganizationsOrgIdRouteChildren {
  OrganizationsOrgIdClubsClubIdRoute: typeof OrganizationsOrgIdClubsClubIdRouteWithChildren
}

const OrganizationsOrgIdRouteChildren: OrganizationsOrgIdRouteChildren = {
  OrganizationsOrgIdClubsClubIdRoute:
    OrganizationsOrgIdClubsClubIdRouteWithChildren,
}

const OrganizationsOrgIdRouteWithChildren =
  OrganizationsOrgIdRoute._addFileChildren(OrganizationsOrgIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ZatcaRoute: ZatcaRoute,
  AuthLoginRoute: AuthLoginRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  OrganizationsOrgIdRoute: OrganizationsOrgIdRouteWithChildren,
  RolesRoleIdRoute: RolesRoleIdRoute,
  MembersIndexRoute: MembersIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
