package com.liyaqa.audit

enum class AuditAction(val code: String) {
    // Member
    MEMBER_CREATED("MEMBER_CREATED"),
    MEMBER_UPDATED("MEMBER_UPDATED"),
    MEMBER_DELETED("MEMBER_DELETED"),

    // Membership
    MEMBERSHIP_ASSIGNED("MEMBERSHIP_ASSIGNED"),
    MEMBERSHIP_RENEWED("MEMBERSHIP_RENEWED"),
    MEMBERSHIP_FROZEN("MEMBERSHIP_FROZEN"),
    MEMBERSHIP_UNFROZEN("MEMBERSHIP_UNFROZEN"),
    MEMBERSHIP_TERMINATED("MEMBERSHIP_TERMINATED"),

    // Payment
    PAYMENT_COLLECTED("PAYMENT_COLLECTED"),
    PAYMENT_REFUNDED("PAYMENT_REFUNDED"),

    // Staff
    STAFF_CREATED("STAFF_CREATED"),
    STAFF_UPDATED("STAFF_UPDATED"),
    STAFF_DELETED("STAFF_DELETED"),

    // Trainer
    TRAINER_CREATED("TRAINER_CREATED"),
    TRAINER_UPDATED("TRAINER_UPDATED"),
    TRAINER_DELETED("TRAINER_DELETED"),

    // GX
    GX_BOOKED("GX_BOOKED"),
    GX_BOOKING_CANCELLED("GX_BOOKING_CANCELLED"),

    // PT
    PT_ATTENDANCE_MARKED("PT_ATTENDANCE_MARKED"),

    // Lead
    LEAD_CREATED("LEAD_CREATED"),
    LEAD_UPDATED("LEAD_UPDATED"),
    LEAD_CONVERTED("LEAD_CONVERTED"),
    LEAD_LOST("LEAD_LOST"),

    // Cash Drawer
    CASH_DRAWER_SESSION_OPENED("CASH_DRAWER_SESSION_OPENED"),
    CASH_DRAWER_SESSION_CLOSED("CASH_DRAWER_SESSION_CLOSED"),
    CASH_DRAWER_ENTRY_ADDED("CASH_DRAWER_ENTRY_ADDED"),

    // Auth
    MEMBER_LOGIN("MEMBER_LOGIN"),

    // Role management
    ROLE_CREATED("ROLE_CREATED"),
    ROLE_UPDATED("ROLE_UPDATED"),
    ROLE_DELETED("ROLE_DELETED"),
    ROLE_PERMISSION_ADDED("ROLE_PERMISSION_ADDED"),
    ROLE_PERMISSION_REMOVED("ROLE_PERMISSION_REMOVED"),
    STAFF_ROLE_ASSIGNED("STAFF_ROLE_ASSIGNED"),

    // Report Builder
    REPORT_TEMPLATE_CREATED("REPORT_TEMPLATE_CREATED"),
    REPORT_TEMPLATE_DELETED("REPORT_TEMPLATE_DELETED"),
    REPORT_RUN("REPORT_RUN"),
}
