package com.liyaqa.audit

enum class AuditAction(val code: String) {
    // Member
    MEMBER_CREATED("MEMBER_CREATED"),
    MEMBER_UPDATED("MEMBER_UPDATED"),
    MEMBER_DELETED("MEMBER_DELETED"),

    // Membership
    MEMBERSHIP_ASSIGNED("MEMBERSHIP_ASSIGNED"),
    MEMBERSHIP_RENEWED("MEMBERSHIP_RENEWED"),
    MEMBERSHIP_FROZEN("MEMBERSHIP_FROZEN"),
    MEMBERSHIP_UNFROZEN("MEMBERSHIP_UNFROZEN"),
    MEMBERSHIP_TERMINATED("MEMBERSHIP_TERMINATED"),

    // Payment
    PAYMENT_COLLECTED("PAYMENT_COLLECTED"),
    PAYMENT_REFUNDED("PAYMENT_REFUNDED"),

    // Staff
    STAFF_CREATED("STAFF_CREATED"),
    STAFF_UPDATED("STAFF_UPDATED"),
    STAFF_DELETED("STAFF_DELETED"),

    // Trainer
    TRAINER_CREATED("TRAINER_CREATED"),
    TRAINER_UPDATED("TRAINER_UPDATED"),
    TRAINER_DELETED("TRAINER_DELETED"),

    // GX
    GX_BOOKED("GX_BOOKED"),
    GX_BOOKING_CANCELLED("GX_BOOKING_CANCELLED"),

    // PT
    PT_ATTENDANCE_MARKED("PT_ATTENDANCE_MARKED"),

    // Lead
    LEAD_CREATED("LEAD_CREATED"),
    LEAD_UPDATED("LEAD_UPDATED"),
    LEAD_CONVERTED("LEAD_CONVERTED"),
    LEAD_LOST("LEAD_LOST"),

    // Cash Drawer
    CASH_DRAWER_SESSION_OPENED("CASH_DRAWER_SESSION_OPENED"),
    CASH_DRAWER_SESSION_CLOSED("CASH_DRAWER_SESSION_CLOSED"),
    CASH_DRAWER_ENTRY_ADDED("CASH_DRAWER_ENTRY_ADDED"),

    // Auth
    MEMBER_LOGIN("MEMBER_LOGIN"),

    // Role management
    ROLE_CREATED("ROLE_CREATED"),
    ROLE_UPDATED("ROLE_UPDATED"),
    ROLE_DELETED("ROLE_DELETED"),
    ROLE_PERMISSION_ADDED("ROLE_PERMISSION_ADDED"),
    ROLE_PERMISSION_REMOVED("ROLE_PERMISSION_REMOVED"),
    STAFF_ROLE_ASSIGNED("STAFF_ROLE_ASSIGNED"),

    // Report Builder
    REPORT_TEMPLATE_CREATED("REPORT_TEMPLATE_CREATED"),
    REPORT_TEMPLATE_DELETED("REPORT_TEMPLATE_DELETED"),
    REPORT_RUN("REPORT_RUN"),

    // Report Schedule
    REPORT_SCHEDULE_CREATED("REPORT_SCHEDULE_CREATED"),
    REPORT_SCHEDULE_UPDATED("REPORT_SCHEDULE_UPDATED"),
    REPORT_SCHEDULE_DELETED("REPORT_SCHEDULE_DELETED"),
    REPORT_EMAIL_SENT("REPORT_EMAIL_SENT"),

    // Self-registration
    MEMBER_SELF_REGISTERED("MEMBER_SELF_REGISTERED"),
    MEMBER_ACTIVATED("MEMBER_ACTIVATED"),

    // ZATCA
    ZATCA_CSID_RENEWED("ZATCA_CSID_RENEWED"),
    ZATCA_INVOICE_RETRY_REQUESTED("ZATCA_INVOICE_RETRY_REQUESTED"),

    // Member Import
    MEMBER_IMPORT_STARTED("MEMBER_IMPORT_STARTED"),
    MEMBER_IMPORT_COMPLETED("MEMBER_IMPORT_COMPLETED"),
    MEMBER_IMPORT_CANCELLED("MEMBER_IMPORT_CANCELLED"),
    MEMBER_IMPORT_ROLLED_BACK("MEMBER_IMPORT_ROLLED_BACK"),

    // Member Note
    MEMBER_NOTE_ADDED("MEMBER_NOTE_ADDED"),
    MEMBER_NOTE_DELETED("MEMBER_NOTE_DELETED"),

    // Lapse Recovery
    MEMBERSHIP_LAPSED("MEMBERSHIP_LAPSED"),
    MEMBER_REACTIVATED("MEMBER_REACTIVATED"),

    // Portal Branding
    BRANDING_UPDATED("BRANDING_UPDATED"),

    // Check-In
    MEMBER_CHECKED_IN("MEMBER_CHECKED_IN"),

    // Shift
    SHIFT_CREATED("SHIFT_CREATED"),
    SHIFT_UPDATED("SHIFT_UPDATED"),
    SHIFT_DELETED("SHIFT_DELETED"),
    SHIFT_SWAP_APPROVED("SHIFT_SWAP_APPROVED"),
    SHIFT_SWAP_REJECTED("SHIFT_SWAP_REJECTED"),
}
