/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MembershipIndexRouteImport } from './routes/membership/index'
import { Route as ClubIndexRouteImport } from './routes/club/index'
import { Route as ClassesIndexRouteImport } from './routes/classes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as SessionsHistoryRouteImport } from './routes/sessions/history'
import { Route as PaymentsInvoicesRouteImport } from './routes/payments/invoices'
import { Route as MembershipUpgradeRouteImport } from './routes/membership/upgrade'
import { Route as MembershipFreezeRouteImport } from './routes/membership/freeze'
import { Route as ClubTrainersRouteImport } from './routes/club/trainers'
import { Route as ClubScheduleRouteImport } from './routes/club/schedule'
import { Route as ClassesMyClassesRouteImport } from './routes/classes/my-classes'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLanguageRouteImport } from './routes/auth/language'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountPreferencesRouteImport } from './routes/account/preferences'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipIndexRoute = MembershipIndexRouteImport.update({
  id: '/membership/',
  path: '/membership/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/club/',
  path: '/club/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsHistoryRoute = SessionsHistoryRouteImport.update({
  id: '/sessions/history',
  path: '/sessions/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsInvoicesRoute = PaymentsInvoicesRouteImport.update({
  id: '/payments/invoices',
  path: '/payments/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipUpgradeRoute = MembershipUpgradeRouteImport.update({
  id: '/membership/upgrade',
  path: '/membership/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipFreezeRoute = MembershipFreezeRouteImport.update({
  id: '/membership/freeze',
  path: '/membership/freeze',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubTrainersRoute = ClubTrainersRouteImport.update({
  id: '/club/trainers',
  path: '/club/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubScheduleRoute = ClubScheduleRouteImport.update({
  id: '/club/schedule',
  path: '/club/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesMyClassesRoute = ClassesMyClassesRouteImport.update({
  id: '/classes/my-classes',
  path: '/classes/my-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLanguageRoute = AuthLanguageRouteImport.update({
  id: '/auth/language',
  path: '/auth/language',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/account/preferences',
  path: '/account/preferences',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/language': typeof AuthLanguageRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/classes/my-classes': typeof ClassesMyClassesRoute
  '/club/schedule': typeof ClubScheduleRoute
  '/club/trainers': typeof ClubTrainersRoute
  '/membership/freeze': typeof MembershipFreezeRoute
  '/membership/upgrade': typeof MembershipUpgradeRoute
  '/payments/invoices': typeof PaymentsInvoicesRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/account/': typeof AccountIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/club/': typeof ClubIndexRoute
  '/membership/': typeof MembershipIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/language': typeof AuthLanguageRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/classes/my-classes': typeof ClassesMyClassesRoute
  '/club/schedule': typeof ClubScheduleRoute
  '/club/trainers': typeof ClubTrainersRoute
  '/membership/freeze': typeof MembershipFreezeRoute
  '/membership/upgrade': typeof MembershipUpgradeRoute
  '/payments/invoices': typeof PaymentsInvoicesRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/account': typeof AccountIndexRoute
  '/classes': typeof ClassesIndexRoute
  '/club': typeof ClubIndexRoute
  '/membership': typeof MembershipIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/language': typeof AuthLanguageRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/classes/my-classes': typeof ClassesMyClassesRoute
  '/club/schedule': typeof ClubScheduleRoute
  '/club/trainers': typeof ClubTrainersRoute
  '/membership/freeze': typeof MembershipFreezeRoute
  '/membership/upgrade': typeof MembershipUpgradeRoute
  '/payments/invoices': typeof PaymentsInvoicesRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/account/': typeof AccountIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/club/': typeof ClubIndexRoute
  '/membership/': typeof MembershipIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/account/preferences'
    | '/account/security'
    | '/auth/forgot-password'
    | '/auth/language'
    | '/auth/login'
    | '/auth/reset-password'
    | '/classes/my-classes'
    | '/club/schedule'
    | '/club/trainers'
    | '/membership/freeze'
    | '/membership/upgrade'
    | '/payments/invoices'
    | '/sessions/history'
    | '/account/'
    | '/classes/'
    | '/club/'
    | '/membership/'
    | '/messages/'
    | '/payments/'
    | '/progress/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/account/preferences'
    | '/account/security'
    | '/auth/forgot-password'
    | '/auth/language'
    | '/auth/login'
    | '/auth/reset-password'
    | '/classes/my-classes'
    | '/club/schedule'
    | '/club/trainers'
    | '/membership/freeze'
    | '/membership/upgrade'
    | '/payments/invoices'
    | '/sessions/history'
    | '/account'
    | '/classes'
    | '/club'
    | '/membership'
    | '/messages'
    | '/payments'
    | '/progress'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/notifications'
    | '/account/preferences'
    | '/account/security'
    | '/auth/forgot-password'
    | '/auth/language'
    | '/auth/login'
    | '/auth/reset-password'
    | '/classes/my-classes'
    | '/club/schedule'
    | '/club/trainers'
    | '/membership/freeze'
    | '/membership/upgrade'
    | '/payments/invoices'
    | '/sessions/history'
    | '/account/'
    | '/classes/'
    | '/club/'
    | '/membership/'
    | '/messages/'
    | '/payments/'
    | '/progress/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificationsRoute: typeof NotificationsRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLanguageRoute: typeof AuthLanguageRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  ClassesMyClassesRoute: typeof ClassesMyClassesRoute
  ClubScheduleRoute: typeof ClubScheduleRoute
  ClubTrainersRoute: typeof ClubTrainersRoute
  MembershipFreezeRoute: typeof MembershipFreezeRoute
  MembershipUpgradeRoute: typeof MembershipUpgradeRoute
  PaymentsInvoicesRoute: typeof PaymentsInvoicesRoute
  SessionsHistoryRoute: typeof SessionsHistoryRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  ClubIndexRoute: typeof ClubIndexRoute
  MembershipIndexRoute: typeof MembershipIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/': {
      id: '/membership/'
      path: '/membership'
      fullPath: '/membership/'
      preLoaderRoute: typeof MembershipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/club'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/history': {
      id: '/sessions/history'
      path: '/sessions/history'
      fullPath: '/sessions/history'
      preLoaderRoute: typeof SessionsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/invoices': {
      id: '/payments/invoices'
      path: '/payments/invoices'
      fullPath: '/payments/invoices'
      preLoaderRoute: typeof PaymentsInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/upgrade': {
      id: '/membership/upgrade'
      path: '/membership/upgrade'
      fullPath: '/membership/upgrade'
      preLoaderRoute: typeof MembershipUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/freeze': {
      id: '/membership/freeze'
      path: '/membership/freeze'
      fullPath: '/membership/freeze'
      preLoaderRoute: typeof MembershipFreezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/trainers': {
      id: '/club/trainers'
      path: '/club/trainers'
      fullPath: '/club/trainers'
      preLoaderRoute: typeof ClubTrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/schedule': {
      id: '/club/schedule'
      path: '/club/schedule'
      fullPath: '/club/schedule'
      preLoaderRoute: typeof ClubScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/my-classes': {
      id: '/classes/my-classes'
      path: '/classes/my-classes'
      fullPath: '/classes/my-classes'
      preLoaderRoute: typeof ClassesMyClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/language': {
      id: '/auth/language'
      path: '/auth/language'
      fullPath: '/auth/language'
      preLoaderRoute: typeof AuthLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/security': {
      id: '/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/account/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificationsRoute: NotificationsRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLanguageRoute: AuthLanguageRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ClassesMyClassesRoute: ClassesMyClassesRoute,
  ClubScheduleRoute: ClubScheduleRoute,
  ClubTrainersRoute: ClubTrainersRoute,
  MembershipFreezeRoute: MembershipFreezeRoute,
  MembershipUpgradeRoute: MembershipUpgradeRoute,
  PaymentsInvoicesRoute: PaymentsInvoicesRoute,
  SessionsHistoryRoute: SessionsHistoryRoute,
  AccountIndexRoute: AccountIndexRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  ClubIndexRoute: ClubIndexRoute,
  MembershipIndexRoute: MembershipIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
